# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fribaamaan' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for Fribaamaan

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'RCTText',
  'RCTImage',
  'RCTNetwork',
  'RCTWebSocket',
]
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

#react-native-maps
pod 'react-native-maps', :path => '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils'

pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

target 'FribaamaanTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Fribaamaan-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Fribaamaan-tvOS

  target 'Fribaamaan-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
